CREATE TABLE IF NOT EXISTS users(
	user_id SERIAL PRIMARY KEY,
	username VARCHAR(50) UNIQUE NOT NULL,
	password VARCHAR(100) NOT NULL,
	created_on TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	last_login TIMESTAMP WITH TIME ZONE,
	last_logout TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS channels(
	channel_id SERIAL PRIMARY KEY,
	channel VARCHAR(50) UNIQUE NOT NULL,
	created_on TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS messages(
	message_id SERIAL PRIMARY KEY,
	user_id INTEGER REFERENCES users(user_id) NOT NULL,
	channel_id INTEGER REFERENCES channels(channel_id) NOT NULL,
	text VARCHAR(512) NOT NULL,
	created_on TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);